import React from 'react';
import Head from 'next/head'

import AccountEditView from '../../views/AccountEditView'

const accounts: React.FC = () => {
  return (
    <div>
        <Head>
            <title>Instagram</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
        <AccountEditView />
    </div>
  );
}

export default accounts;