import { useEffect, useRef } from "react";
import Head from "next/head";
import Login from "../views/LogIn";
import HomeView from "../views/HomeView";

import { isAuthenticated } from "../service/token";

const Home: React.FC = () => {
  const loged = useRef(null);

  useEffect(() => {
    loged.current = isAuthenticated();
  }, []);

  return (
    <div>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {loged.current ? <HomeView /> : <Login />}
    </div>
  );
};

export default Home;
