import React from "react";
import Head from "next/head";
import SigninView from "../views/SigninView";

const Signin: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <SigninView />
    </div>
  );
};

export default Signin;
