import React from "react";
import Head from "next/head";
import PostPage from "../../views/PostPage";

const Perfil: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <PostPage />
    </div>
  );
};

export default Perfil;
